# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  # - linux # Linux does not easily support OpenCL on Travis
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
branches:
  only: # Only kick off CI for master and potential merges to master from within PRs
    - master
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "0.7" ] && [ $TRAVIS_OS_NAME = "linux" ]; then
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
    fi
