# http://lint.travis-ci.org/
language: julia
os:
  - linux
julia:
  - 0.4
  - nightly
notifications:
  email: false
addons:
  apt:
    packages:
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # X virtual framebuffer
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Descartes"); Pkg.test("Descartes"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Descartes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
