# http://lint.travis-ci.org/
language: julia
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
julia:
  - release
  - nightly
notifications:
  email: false
addons:
  apt:
    packages:
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # X virtual framebuffer

